name: Update Coursework Activity

on:
  schedule:
    - cron: '0 4 * * 1'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout .github repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.COURSEWORK_PAT }}
          fetch-depth: 0

      - name: Checkout target repo (Coursework-Archive/.github)
        uses: actions/checkout@v3
        with:
          repository: Coursework-Archive/.github
          token: ${{ secrets.COURSEWORK_PAT }}
          path: target

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install python-dateutil

      - name: Run activity script and update README
        run: python scripts/update-coursework-activity.py
        working-directory: .

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "🤖 Update coursework activity"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.COURSEWORK_PAT }}
