name: Update Coursework Activity

on:
  schedule:
    # Every Monday at 04:00 UTC
    - cron: '0 4 * * 1'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install python-dateutil

      - name: Run activity script and update README
        run: python scripts/update-coursework-activity.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "🤖 Update coursework activity"
          git push
