name: Update Org Activity Table

permissions:
  contents: write
  
# run every Monday at 04:00 UTC, or manually via the UI
on:
  schedule:
    - cron: '0 4 * * 1'
  workflow_dispatch:

jobs:
  update-activity:
    runs-on: ubuntu-latest

    steps:
      # 1) pull down the .github repo (so we get profile/README.md, scripts/, workflows/)
      - uses: actions/checkout@v3
        with:
          persist-credentials: true   # ensures the checkout step sets up auth for git push

      # 2) get Python available
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) install the two external libs your script uses
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      # 4) run your updater script
      - name: Update profile README
        run: python scripts/update-coursework-activity.py

      - name: Dump generated table
        run: |
          echo "::group::ACTIVITY section from profile/README.md"
          sed -n '/<!-- ACTIVITY-TABLE:START -->/,/<!-- ACTIVITY-TABLE:END -->/p' profile/README.md
          echo "::endgroup::"


      # 5) commit & push back any changes to profile/README.md
      - name: Commit & push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # configure git
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # stage the only file that changed
          git add profile/README.md

          # commit if there *are* changes, otherwise skip
          if git diff --cached --quiet; then
            echo "Nothing to commit"
          else
            git commit -m "chore: auto-update activity table"
            git push
          fi
